import { test, expect, Page } from '@playwright/test';
	
test('check open form login', async ({ page }) => {
	test.setTimeout(60000);
		const btnComeIn1 = page.getByTestId('mailbox').getByRole('button', { name: 'Войти' });
 		const inputFormLogin = page.frameLocator('.ag-popup__frame__layout__iframe').getByPlaceholder('Имя аккаунта');
    const btnComeInFormLogin = page.frameLocator('.ag-popup__frame__layout__iframe').locator('[data-test-id="next-button"]');
    const headerFormPassword = page.getByRole('heading', { name: 'Введите пароль' });
		const formPassword = page.frameLocator('.ag-popup__frame__layout__iframe').getByPlaceholder('Пароль');
		const btnComeIn2 = page.frameLocator('.ag-popup__frame__layout__iframe').locator('[data-test-id="submit-button"]');
    await page.goto('https://mail.ru/');
    await btnComeIn1.waitFor({ state: 'visible' });
		expect (await btnComeIn1.isVisible()).toBe(true);
		await btnComeIn1.click();
		await inputFormLogin.click();
		await inputFormLogin.fill('misterbinqa');
		await btnComeInFormLogin.click();
		await formPassword.fill('privetmrbin');
		await btnComeIn2.click();
		await page.getByRole('link', { name: 'Почта 5' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Облако' }).click();
  const page1 = await page1Promise;
  const page2Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Календарь' }).click();
  const page2 = await page2Promise;
  await page2.goto('https://x.calendar.mail.ru/?utm_source=portal&utm_medium=portal_navigation_under_search_exp&utm_campaign=x.calendar.mail.ru&mt_click_id=mt-wim9e3-1687613188-1960210612&mt_sub1=e.mail.ru');
  await page2.goto('https://x.calendar.mail.ru/month/today/?utm_source=portal&utm_medium=portal_navigation_under_search_exp&utm_campaign=x.calendar.mail.ru&mt_click_id=mt-wim9e3-1687613188-1960210612&mt_sub1=e.mail.ru');
  const page3Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Задачи' }).click();
  const page3 = await page3Promise;
  const page4Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Контакты' }).click();
  const page4 = await page4Promise;
  const page5Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Звонки' }).click();
  const page5 = await page5Promise;
  await page.getByText('Все проекты').click();
  await page.locator('.ph-marusia').click();
  await page.getByRole('img', { name: 'misterbinqa@mail.ru' }).click();
  await page.getByRole('link', { name: 'Социальные сети' }).click();
  await page.getByRole('link', { name: 'Госписьма' }).click();
  await page.getByRole('link', { name: 'Чеки' }).click();
  await page.getByRole('link', { name: 'Отправленные' }).click();
  await page.getByRole('link', { name: 'Черновики' }).click();
  await page.getByRole('link', { name: 'Спам' }).click();
  await page.getByRole('link', { name: 'Корзина' }).click();
	await page.getByText('Новая папка').click();
  await page.locator('[data-test-id="cancel"]').click();
  await page.getByRole('link', { name: 'Почта 5' }).click();
  await page.locator('#app-canvas').getByText('Выделить все').click();
  await page.locator('#app-canvas').getByText('Снять выделение').click();
  await page.getByText('Отметить все прочитанными').click();
  await page.getByText('Отменить').click();
  await page.locator('#app-canvas').getByText('Фильтр').click();
		
});